/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.atomos;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.felix.atomos.Atomos;
import org.apache.felix.atomos.AtomosContent;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleException;
import org.osgi.framework.Constants;
import org.osgi.framework.launch.Framework;
import org.osgi.framework.startlevel.BundleStartLevel;
import org.osgi.framework.startlevel.FrameworkStartLevel;

public final class KuraAtomosLauncher {

    private static final Pattern PLUGINS_LEVEL = Pattern.compile("/plugins/([0-9]+)(s?)/[^/]+\\.jar");
    private static final String DEFAULT_KURA_HOME = "/opt/eclipse/kura";
    private static final String STORAGE = "/tmp/.kura/atomos";
    private static final String DUMP_PROPERTY = "kura.atomos.dump";
    private static final int PARKING_LEVEL = 99;
    private static final Set<String> DROPPED_KEYS = Set.of("osgi.framework", "osgi.bundles", "osgi.clean",
            "osgi.framework.extensions", "osgi.configuration.cascaded");

    private KuraAtomosLauncher() {
    }

    public static void main(String[] args) throws Exception {
        String kuraHome = System.getProperty("kura.home", DEFAULT_KURA_HOME);
        Map<String, String> config = frameworkConfiguration(Paths.get(kuraHome, "framework", "config.ini"));

        long t0 = System.nanoTime();
        Atomos atomos = Atomos.newAtomos(config);
        Framework framework = atomos.newFramework(config);
        framework.init();
        framework.adapt(FrameworkStartLevel.class).setInitialBundleStartLevel(PARKING_LEVEL);
        if (Boolean.getBoolean("kura.atomos.diag")) {
            traceUnregistrations(framework);
        }
        List<String> report = installContents(atomos);
        framework.adapt(org.osgi.framework.wiring.FrameworkWiring.class).resolveBundles(null);
        framework.start();
        if (Boolean.getBoolean("kura.atomos.diag")) {
            long active = java.util.Arrays.stream(framework.getBundleContext().getBundles())
                    .filter(b -> b.getState() == Bundle.ACTIVE || b.getState() == Bundle.STARTING).count();
            System.out.println("after framework.start(): framework level="
                    + framework.adapt(FrameworkStartLevel.class).getStartLevel() + " active/starting bundles=" + active);
        }
        raiseStartLevel(framework, Integer.getInteger("kura.atomos.startLevel", 6));
        long startedMs = (System.nanoTime() - t0) / 1_000_000;

        if (Boolean.getBoolean(DUMP_PROPERTY)) {
            dump(framework, report, startedMs);
            int again = Integer.getInteger("kura.atomos.dumpAfter", 0);
            if (again > 0) {
                Thread.sleep(again * 1000L);
                System.out.println("=== after " + again + " s ===");
                dump(framework, List.of(), startedMs);
                if (Boolean.getBoolean("kura.atomos.diag")) {
                    scrDiag(framework);
                }
            }
        }
        framework.waitForStop(0);
        System.exit(0);
    }

    private static Map<String, String> frameworkConfiguration(Path configIni) throws IOException {
        Map<String, String> config = new HashMap<>();
        if (Files.exists(configIni)) {
            Properties props = new Properties();
            try (InputStream in = Files.newInputStream(configIni)) {
                props.load(in);
            }
            props.stringPropertyNames().stream().filter(k -> !DROPPED_KEYS.contains(k))
                    .forEach(k -> config.put(k, props.getProperty(k)));
        }
        config.put(Constants.FRAMEWORK_STORAGE, System.getProperty("kura.atomos.storage", STORAGE));
        config.put(Constants.FRAMEWORK_STORAGE_CLEAN, Constants.FRAMEWORK_STORAGE_CLEAN_ONFIRSTINIT);
        config.put(Atomos.ATOMOS_CONTENT_START, "false");
        config.put(Atomos.ATOMOS_CONTENT_INSTALL, "false");
        config.putIfAbsent("osgi.bundles.defaultStartLevel", "5");
        config.put(Constants.FRAMEWORK_BEGINNING_STARTLEVEL, "1");
        return config;
    }

    private static List<String> installContents(Atomos atomos) {
        List<String> report = new ArrayList<>();
        Set<AtomosContent> contents = atomos.getBootLayer().getAtomosContents();
        report.add("boot layer contents: " + contents.size());
        for (AtomosContent content : contents) {
            if (content.getBundle() != null) {
                continue;
            }
            Bundle bundle;
            try {
                bundle = content.install();
            } catch (BundleException e) {
                report.add("install failed: " + content.getSymbolicName() + ": " + e.getMessage().replace('\n', ' '));
                continue;
            }
            if (bundle == null || content.getAtomosLocation().startsWith("boot:jrt:")) {
                continue;
            }
            Matcher m = PLUGINS_LEVEL.matcher(content.getAtomosLocation());
            int level;
            boolean start;
            if (m.find()) {
                level = Integer.parseInt(m.group(1));
                start = !m.group(2).isEmpty();
            } else {
                report.add("no level, starting at 1: " + content.getSymbolicName() + " " + content.getAtomosLocation());
                level = 1;
                start = true;
            }
            bundle.adapt(BundleStartLevel.class).setStartLevel(level);
            if (start) {
                try {
                    bundle.start();
                } catch (BundleException e) {
                    report.add("start failed: " + content.getSymbolicName() + ": " + e.getMessage().replace('\n', ' '));
                }
            }
        }
        return report;
    }

    private static void raiseStartLevel(Framework framework, int target) throws InterruptedException {
        CountDownLatch reached = new CountDownLatch(1);
        framework.adapt(FrameworkStartLevel.class).setStartLevel(target, event -> reached.countDown());
        reached.await(5, TimeUnit.MINUTES);
    }

    private static void dump(Framework framework, List<String> report, long startedMs) {
        FrameworkStartLevel fsl = framework.adapt(FrameworkStartLevel.class);
        System.out.println("framework started in " + startedMs + " ms, start level " + fsl.getStartLevel());
        report.forEach(System.out::println);
        Map<Integer, Integer> byState = new HashMap<>();
        for (Bundle b : framework.getBundleContext().getBundles()) {
            if (b.getSymbolicName() == null || b.getSymbolicName().startsWith("java.") || b.getSymbolicName().startsWith("jdk.")) {
                continue;
            }
            byState.merge(b.getState(), 1, Integer::sum);
            if (b.getState() != Bundle.ACTIVE) {
                System.out.printf("%-10s %3d %s %s %s%n", stateName(b.getState()),
                        b.adapt(BundleStartLevel.class).getStartLevel(), b.getSymbolicName(), b.getVersion(),
                        Boolean.getBoolean("kura.atomos.trace") ? b.getLocation() : "");
                if (b.getState() == Bundle.INSTALLED && Boolean.getBoolean("kura.atomos.diag")) {
                    try {
                        b.start(Bundle.START_TRANSIENT);
                    } catch (BundleException e) {
                        e.getMessage().lines().filter(l -> l.contains("Unresolved requirement")).limit(4)
                                .forEach(l -> System.out.println("      " + l.trim()));
                    }
                }
            }
        }
        System.out.println("bundles by state: " + byState.entrySet().stream()
                .map(e -> stateName(e.getKey()) + "=" + e.getValue()).toList());
    }

    private static void traceUnregistrations(Framework framework) {
        java.util.concurrent.atomic.AtomicInteger stacks = new java.util.concurrent.atomic.AtomicInteger();
        framework.getBundleContext().addServiceListener(event -> {
            if (event.getType() != org.osgi.framework.ServiceEvent.UNREGISTERING) {
                return;
            }
            org.osgi.framework.ServiceReference<?> ref = event.getServiceReference();
            String[] classes = (String[]) ref.getProperty(Constants.OBJECTCLASS);
            if (!classes[0].startsWith("org.eclipse.kura")) {
                return;
            }
            System.out.println("UNREGISTERING " + classes[0] + " pid=" + ref.getProperty("kura.service.pid") + " bundle="
                    + ref.getBundle().getSymbolicName() + " thread=" + Thread.currentThread().getName());
            if (stacks.getAndIncrement() < 2) {
                for (StackTraceElement e : Thread.currentThread().getStackTrace()) {
                    String c = e.getClassName();
                    if (!c.startsWith("java.") && !c.startsWith("jdk.") && !c.contains("EventManager")) {
                        System.out.println("    at " + e);
                    }
                }
            }
        });
    }

    private static void scrDiag(Framework framework) {
        org.osgi.framework.BundleContext ctx = framework.getBundleContext();
        Map<String, List<String>> census = new java.util.TreeMap<>();
        try {
            for (org.osgi.framework.ServiceReference<?> ref : ctx.getAllServiceReferences(null, null)) {
                for (String oc : (String[]) ref.getProperty(Constants.OBJECTCLASS)) {
                    if (oc.startsWith("org.eclipse.kura") || oc.startsWith("org.osgi.service")) {
                        census.computeIfAbsent(oc, k -> new ArrayList<>()).add(ref.getBundle().getSymbolicName() + "#"
                                + ref.getProperty(Constants.SERVICE_ID) + " pid=" + ref.getProperty("kura.service.pid"));
                    }
                }
            }
        } catch (org.osgi.framework.InvalidSyntaxException e) {
            throw new IllegalStateException(e);
        }
        System.out.println("--- services registered more than once:");
        census.entrySet().stream().filter(e -> e.getValue().size() > 1)
                .forEach(e -> System.out.println(e.getKey() + " x" + e.getValue().size() + " " + e.getValue()));
        org.osgi.framework.ServiceReference<org.osgi.service.component.runtime.ServiceComponentRuntime> scrRef = ctx
                .getServiceReference(org.osgi.service.component.runtime.ServiceComponentRuntime.class);
        if (scrRef == null) {
            System.out.println("--- no ServiceComponentRuntime");
            return;
        }
        org.osgi.service.component.runtime.ServiceComponentRuntime scr = ctx.getService(scrRef);
        System.out.println("--- component configurations not satisfied/active:");
        for (org.osgi.service.component.runtime.dto.ComponentDescriptionDTO d : scr.getComponentDescriptionDTOs()) {
            for (org.osgi.service.component.runtime.dto.ComponentConfigurationDTO c : scr.getComponentConfigurationDTOs(d)) {
                if (c.state != org.osgi.service.component.runtime.dto.ComponentConfigurationDTO.ACTIVE
                        && c.state != org.osgi.service.component.runtime.dto.ComponentConfigurationDTO.SATISFIED) {
                    System.out.println(d.name + " state=" + c.state + " failure=" + c.failure);
                    for (org.osgi.service.component.runtime.dto.UnsatisfiedReferenceDTO u : c.unsatisfiedReferences) {
                        System.out.println("    unsatisfied " + u.name + " " + u.target);
                    }
                }
            }
        }
        ctx.ungetService(scrRef);
    }

    private static String stateName(int state) {
        return switch (state) {
        case Bundle.ACTIVE -> "ACTIVE";
        case Bundle.RESOLVED -> "RESOLVED";
        case Bundle.INSTALLED -> "INSTALLED";
        case Bundle.STARTING -> "STARTING";
        case Bundle.STOPPING -> "STOPPING";
        default -> "UNINSTALLED";
        };
    }
}
