/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.atomos;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.felix.atomos.Atomos;
import org.apache.felix.atomos.AtomosContent;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;
import org.osgi.framework.BundleException;
import org.osgi.framework.Constants;
import org.osgi.framework.ServiceReference;
import org.osgi.framework.launch.Framework;
import org.osgi.framework.startlevel.BundleStartLevel;
import org.osgi.framework.startlevel.FrameworkStartLevel;

public final class KuraAtomosLauncher {

    private static final Pattern PLUGINS_LEVEL = Pattern.compile("(?:/plugins/([0-9]+)(s?)/[^/]+\\.jar|(?:^|[/:])([0-9]+)(s?)__[^/]+\\.jar)");
    private static final String DEFAULT_KURA_HOME = "/opt/eclipse/kura";
    private static final String STORAGE = "/tmp/.kura/atomos";
    private static final String DUMP_PROPERTY = "kura.atomos.dump";
    private static final int PARKING_LEVEL = 99;
    private static final Set<String> DROPPED_KEYS = Set.of("osgi.framework", "osgi.bundles", "osgi.clean",
            "osgi.framework.extensions", "osgi.configuration.cascaded");

    private KuraAtomosLauncher() {
    }

    public static void main(String[] args) throws Exception {
        String kuraHome = System.getProperty("kura.home", DEFAULT_KURA_HOME);
        Map<String, String> config = frameworkConfiguration(Paths.get(kuraHome, "framework", "config.ini"));

        long t0 = System.nanoTime();
        Atomos atomos = Atomos.newAtomos(config);
        Framework framework = atomos.newFramework(config);
        framework.init();
        framework.adapt(FrameworkStartLevel.class).setInitialBundleStartLevel(PARKING_LEVEL);
        if (Boolean.getBoolean("kura.atomos.diag")) {
            traceUnregistrations(framework);
            traceLogService(framework);
        }
        List<String> report = installContents(atomos);
        framework.adapt(org.osgi.framework.wiring.FrameworkWiring.class).resolveBundles(null);
        framework.start();
        if (Boolean.getBoolean("kura.atomos.diag")) {
            long active = java.util.Arrays.stream(framework.getBundleContext().getBundles())
                    .filter(b -> b.getState() == Bundle.ACTIVE || b.getState() == Bundle.STARTING).count();
            System.out.println("after framework.start(): framework level="
                    + framework.adapt(FrameworkStartLevel.class).getStartLevel() + " active/starting bundles=" + active);
        }
        raiseStartLevel(framework, Integer.getInteger("kura.atomos.startLevel", 6));
        long startedMs = (System.nanoTime() - t0) / 1_000_000;
        if (System.getProperty("kura.atomos.diag.comm") != null) {
            commDiag(framework.getBundleContext(), System.getProperty("kura.atomos.diag.comm"));
        }
        if (Boolean.getBoolean("kura.atomos.diag.hid")) {
            hidDiag(framework.getBundleContext());
        }

        if (Boolean.getBoolean(DUMP_PROPERTY)) {
            dump(framework, report, startedMs);
            int again = Integer.getInteger("kura.atomos.dumpAfter", 0);
            if (again > 0) {
                Thread.sleep(again * 1000L);
                System.out.println("=== after " + again + " s ===");
                dump(framework, List.of(), startedMs);
                if (Boolean.getBoolean("kura.atomos.diag")) {
                    scrDiag(framework);
                }
            }
        }
        framework.waitForStop(0);
        System.exit(0);
    }

    private static Map<String, String> frameworkConfiguration(Path configIni) throws IOException {
        Map<String, String> config = new HashMap<>();
        if (Files.exists(configIni)) {
            Properties props = new Properties();
            try (InputStream in = Files.newInputStream(configIni)) {
                props.load(in);
            }
            props.stringPropertyNames().stream().filter(k -> !DROPPED_KEYS.contains(k))
                    .forEach(k -> config.put(k, props.getProperty(k)));
        }
        config.put(Constants.FRAMEWORK_STORAGE, System.getProperty("kura.atomos.storage", STORAGE));
        config.put(Constants.FRAMEWORK_STORAGE_CLEAN, Constants.FRAMEWORK_STORAGE_CLEAN_ONFIRSTINIT);
        config.put(Atomos.ATOMOS_CONTENT_START, "false");
        config.put(Atomos.ATOMOS_CONTENT_INSTALL, "false");
        System.getProperties().stringPropertyNames().stream().filter(k -> k.startsWith("atomos."))
                .forEach(k -> config.put(k, System.getProperty(k)));
        config.putIfAbsent("osgi.bundles.defaultStartLevel", "5");
        config.put(Constants.FRAMEWORK_BEGINNING_STARTLEVEL, "1");
        return config;
    }

    private static List<String> installContents(Atomos atomos) {
        List<String> report = new ArrayList<>();
        Set<AtomosContent> contents = atomos.getBootLayer().getAtomosContents();
        report.add("boot layer contents: " + contents.size());
        for (AtomosContent content : contents) {
            if (content.getBundle() != null) {
                continue;
            }
            Bundle bundle;
            try {
                bundle = content.install();
            } catch (BundleException e) {
                report.add("install failed: " + content.getSymbolicName() + ": " + e.getMessage().replace('\n', ' '));
                continue;
            }
            if (bundle == null || content.getAtomosLocation().startsWith("boot:jrt:")) {
                continue;
            }
            Matcher m = PLUGINS_LEVEL.matcher(content.getAtomosLocation());
            int level;
            boolean start;
            if (m.find()) {
                level = Integer.parseInt(m.group(1) != null ? m.group(1) : m.group(3));
                start = !(m.group(1) != null ? m.group(2) : m.group(4)).isEmpty();
            } else {
                report.add("no level, starting at 1: " + content.getSymbolicName() + " " + content.getAtomosLocation());
                level = 1;
                start = true;
            }
            bundle.adapt(BundleStartLevel.class).setStartLevel(level);
            if (start) {
                try {
                    bundle.start();
                } catch (BundleException e) {
                    report.add("start failed: " + content.getSymbolicName() + ": " + e.getMessage().replace('\n', ' '));
                }
            }
        }
        return report;
    }

    private static void raiseStartLevel(Framework framework, int target) throws InterruptedException {
        CountDownLatch reached = new CountDownLatch(1);
        framework.adapt(FrameworkStartLevel.class).setStartLevel(target, event -> reached.countDown());
        reached.await(5, TimeUnit.MINUTES);
    }

    private static void dump(Framework framework, List<String> report, long startedMs) {
        FrameworkStartLevel fsl = framework.adapt(FrameworkStartLevel.class);
        System.out.println("framework started in " + startedMs + " ms, start level " + fsl.getStartLevel());
        report.forEach(System.out::println);
        Map<Integer, Integer> byState = new HashMap<>();
        for (Bundle b : framework.getBundleContext().getBundles()) {
            if (b.getSymbolicName() == null || b.getSymbolicName().startsWith("java.") || b.getSymbolicName().startsWith("jdk.")) {
                continue;
            }
            byState.merge(b.getState(), 1, Integer::sum);
            if (b.getState() != Bundle.ACTIVE) {
                System.out.printf("%-10s %3d %s %s %s%n", stateName(b.getState()),
                        b.adapt(BundleStartLevel.class).getStartLevel(), b.getSymbolicName(), b.getVersion(),
                        Boolean.getBoolean("kura.atomos.trace") ? b.getLocation() : "");
                if (b.getState() == Bundle.INSTALLED && Boolean.getBoolean("kura.atomos.diag")) {
                    try {
                        b.start(Bundle.START_TRANSIENT);
                    } catch (BundleException e) {
                        e.getMessage().lines().filter(l -> l.contains("Unresolved requirement")).limit(4)
                                .forEach(l -> System.out.println("      " + l.trim()));
                    }
                }
            }
        }
        System.out.println("bundles by state: " + byState.entrySet().stream()
                .map(e -> stateName(e.getKey()) + "=" + e.getValue()).toList());
    }

    private static void traceUnregistrations(Framework framework) {
        java.util.concurrent.atomic.AtomicInteger stacks = new java.util.concurrent.atomic.AtomicInteger();
        framework.getBundleContext().addServiceListener(event -> {
            if (event.getType() != org.osgi.framework.ServiceEvent.UNREGISTERING) {
                return;
            }
            org.osgi.framework.ServiceReference<?> ref = event.getServiceReference();
            String[] classes = (String[]) ref.getProperty(Constants.OBJECTCLASS);
            if (!classes[0].startsWith("org.eclipse.kura")) {
                return;
            }
            System.out.println("UNREGISTERING " + classes[0] + " pid=" + ref.getProperty("kura.service.pid") + " bundle="
                    + ref.getBundle().getSymbolicName() + " thread=" + Thread.currentThread().getName());
            if (stacks.getAndIncrement() < 2) {
                for (StackTraceElement e : Thread.currentThread().getStackTrace()) {
                    String c = e.getClassName();
                    if (!c.startsWith("java.") && !c.startsWith("jdk.") && !c.contains("EventManager")) {
                        System.out.println("    at " + e);
                    }
                }
            }
        });
    }

    private static void traceLogService(Framework framework) {
        org.osgi.framework.BundleContext ctx = framework.getBundleContext();
        ServiceReference<org.osgi.service.log.LogReaderService> ref = ctx.getServiceReference(org.osgi.service.log.LogReaderService.class);
        if (ref == null) {
            System.out.println("no LogReaderService");
            return;
        }
        ctx.getService(ref).addLogListener(entry -> {
            if (entry.getLogLevel().ordinal() <= org.osgi.service.log.LogLevel.WARN.ordinal()) {
                System.out.println("OSGI LOG " + entry.getLogLevel() + " [" + entry.getLoggerName() + "] " + entry.getMessage()
                        + (entry.getException() != null ? " -> " + entry.getException() : ""));
                Throwable t = entry.getException();
                for (int depth = 0; t != null && depth < 4; t = t.getCause(), depth++) {
                    for (StackTraceElement e : t.getStackTrace()) {
                        if (e.getClassName().startsWith("org.eclipse.kura") || e.getClassName().startsWith("org.h2")) {
                            System.out.println("    at " + e);
                        }
                    }
                    if (t.getCause() != null) {
                        System.out.println("  caused by " + t.getCause());
                    }
                }
            }
        });
    }

    private static void scrDiag(Framework framework) {
        org.osgi.framework.BundleContext ctx = framework.getBundleContext();
        Map<String, List<String>> census = new java.util.TreeMap<>();
        try {
            org.osgi.framework.ServiceReference<?>[] refs = ctx.getAllServiceReferences(null, null);
            for (org.osgi.framework.ServiceReference<?> ref : refs == null ? new org.osgi.framework.ServiceReference<?>[0] : refs) {
                for (String oc : (String[]) ref.getProperty(Constants.OBJECTCLASS)) {
                    if (oc.startsWith("org.eclipse.kura") || oc.startsWith("org.osgi.service")) {
                        census.computeIfAbsent(oc, k -> new ArrayList<>()).add(ref.getBundle().getSymbolicName() + "#"
                                + ref.getProperty(Constants.SERVICE_ID) + " pid=" + ref.getProperty("kura.service.pid"));
                    }
                }
            }
        } catch (org.osgi.framework.InvalidSyntaxException e) {
            throw new IllegalStateException(e);
        }
        System.out.println("--- services registered more than once:");
        census.entrySet().stream().filter(e -> e.getValue().size() > 1)
                .forEach(e -> System.out.println(e.getKey() + " x" + e.getValue().size() + " " + e.getValue()));
        org.osgi.framework.ServiceReference<org.osgi.service.component.runtime.ServiceComponentRuntime> scrRef = ctx
                .getServiceReference(org.osgi.service.component.runtime.ServiceComponentRuntime.class);
        if (scrRef == null) {
            System.out.println("--- no ServiceComponentRuntime");
            return;
        }
        org.osgi.service.component.runtime.ServiceComponentRuntime scr = ctx.getService(scrRef);
        String filter = System.getProperty("kura.atomos.diag.filter");
        System.out.println("--- component configurations not satisfied/active" + (filter == null ? ":" : ", plus all matching " + filter + ":"));
        for (org.osgi.service.component.runtime.dto.ComponentDescriptionDTO d : scr.getComponentDescriptionDTOs()) {
            boolean matches = filter != null && d.name.matches(filter);
            if (matches && scr.getComponentConfigurationDTOs(d).isEmpty()) {
                System.out.println(d.name + " has no configuration (policy=" + d.configurationPolicy + ", factory=" + d.factory
                        + ", enabled=" + scr.isComponentEnabled(d) + ")");
            }
            for (org.osgi.service.component.runtime.dto.ComponentConfigurationDTO c : scr.getComponentConfigurationDTOs(d)) {
                if (matches) {
                    System.out.println(d.name + " state=" + c.state + " pid=" + c.properties.get("kura.service.pid") + " services="
                            + Arrays.toString(d.serviceInterfaces));
                }
                if (c.state != org.osgi.service.component.runtime.dto.ComponentConfigurationDTO.ACTIVE
                        && c.state != org.osgi.service.component.runtime.dto.ComponentConfigurationDTO.SATISFIED) {
                    System.out.println(d.name + " state=" + c.state + " failure=" + c.failure);
                    for (org.osgi.service.component.runtime.dto.UnsatisfiedReferenceDTO u : c.unsatisfiedReferences) {
                        System.out.println("    unsatisfied " + u.name + " " + u.target);
                    }
                }
            }
        }
        ctx.ungetService(scrRef);
    }

    private static void commDiag(BundleContext ctx, String port) {
        String uri = "comm:" + port + ";baudrate=9600;databits=8;stopbits=1;parity=0;flowcontrol=0;timeout=2000;receivetimeout=500";
        ServiceReference<?>[] refs = null;
        try {
            refs = ctx.getServiceReferences("org.osgi.service.io.ConnectionFactory", "(io.scheme=comm)");
            if (refs == null) {
                System.out.println("comm diag: no comm ConnectionFactory registered");
                return;
            }
            Object factory = ctx.getService(refs[0]);
            Method create = factory.getClass().getMethod("createConnection", String.class, int.class, boolean.class);
            Class<?> commConnection = refs[0].getBundle().loadClass("org.eclipse.kura.comm.CommConnection");
            Object connection = create.invoke(factory, uri, 3, true);
            try (OutputStream out = (OutputStream) commConnection.getMethod("openOutputStream").invoke(connection);
                    InputStream in = (InputStream) commConnection.getMethod("openInputStream").invoke(connection)) {
                out.write("AT\r\n".getBytes(StandardCharsets.US_ASCII));
                out.flush();
                System.out.println("comm diag: opened " + uri + ", wrote 4 bytes, available=" + in.available());
            } finally {
                commConnection.getMethod("close").invoke(connection);
            }
        } catch (Exception e) {
            Throwable cause = e instanceof InvocationTargetException ? e.getCause() : e;
            System.out.println("comm diag failed for " + uri + ": " + cause + (cause.getCause() != null ? " <- " + cause.getCause() : ""));
        } finally {
            if (refs != null) {
                ctx.ungetService(refs[0]);
            }
        }
    }

    private static void hidDiag(BundleContext ctx) {
        try {
            Bundle hid = Arrays.stream(ctx.getBundles()).filter(b -> "com.codeminders.hidapi".equals(b.getSymbolicName()))
                    .findFirst().orElse(null);
            if (hid == null) {
                System.out.println("hid diag: hidapi bundle not present");
                return;
            }
            Class<?> manager = hid.loadClass("com.codeminders.hidapi.HIDManager");
            Object instance = manager.getMethod("getInstance").invoke(null);
            Object[] devices = (Object[]) manager.getMethod("listDevices").invoke(instance);
            System.out.println("hid diag: hidapi native library loaded, devices=" + (devices == null ? 0 : devices.length));
        } catch (Exception | LinkageError e) {
            Throwable cause = e instanceof InvocationTargetException ? e.getCause() : e;
            System.out.println("hid diag failed: " + cause + (cause.getCause() != null ? " <- " + cause.getCause() : ""));
        }
    }

    private static String stateName(int state) {
        return switch (state) {
        case Bundle.ACTIVE -> "ACTIVE";
        case Bundle.RESOLVED -> "RESOLVED";
        case Bundle.INSTALLED -> "INSTALLED";
        case Bundle.STARTING -> "STARTING";
        case Bundle.STOPPING -> "STOPPING";
        default -> "UNINSTALLED";
        };
    }
}
